"""Initial migration

Revision ID: 00da822ebe17
Revises:
Create Date: 2026-06-18 11:21:02.640174

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "00da822ebe17"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("order_items_product_id_fkey"), "order_items", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("order_items_order_id_fkey"), "order_items", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "order_items", "orders", ["order_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "order_items", "products", ["product_id"], ["id"], ondelete="RESTRICT"
    )
    op.drop_constraint(op.f("orders_user_id_fkey"), "orders", type_="foreignkey")
    op.create_foreign_key(
        None, "orders", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.alter_column("products", "description", existing_type=sa.TEXT(), nullable=True)
    op.alter_column(
        "users",
        "name",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=100),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "name",
        existing_type=sa.String(length=100),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
    )
    op.alter_column("products", "description", existing_type=sa.TEXT(), nullable=False)
    op.drop_constraint(None, "orders", type_="foreignkey")
    op.create_foreign_key(
        op.f("orders_user_id_fkey"), "orders", "users", ["user_id"], ["id"]
    )
    op.drop_constraint(None, "order_items", type_="foreignkey")
    op.drop_constraint(None, "order_items", type_="foreignkey")
    op.create_foreign_key(
        op.f("order_items_order_id_fkey"), "order_items", "orders", ["order_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("order_items_product_id_fkey"),
        "order_items",
        "products",
        ["product_id"],
        ["id"],
    )
    # ### end Alembic commands ###
